# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jF2q6heZoBmpxshmDTaK88cRfnBSOKy
"""

from math import inf
from collections import deque
import numpy as np
import random
import csv
import matplotlib.pyplot as plt
from matplotlib import colors
import os

np.set_printoptions(suppress=True, precision=2)

class Client:
  def __init__(self, id, arrival_time, service_start_time, service_end_time):
    self.id = id
    self.arrival_time = float(arrival_time)
    self.service_start_time = (float(service_start_time) if service_start_time is not None else None)
    self.service_end_time = (float(service_end_time) if service_end_time is not None else None)

  def get_queue_time(self):
    return self.service_start_time - self.arrival_time

  def get_service_time(self):
    return self.service_end_time - self.service_start_time

  def get_total_time(self):
    return self.service_end_time - self.arrival_time

class Server:
  def __init__(self, id, status, time_to_free):
    self.id = id
    self.status = status
    self.time_to_free = time_to_free

day_profiles = ["Weekday", "Friday", "Saturday", "Sunday"]
config = {}

def start_menu():
  print("\nRetail Queue Simulator")
  print("----------------------")
  print("1 — Demo mode (fast run with realistic defaults)")
  print("2 — Manual configuration")
  while True:
    choice = input("Choose mode: ").strip()
    if choice == "" or choice == "1":
      demo_config = {
        "day": "Weekday",
        "number_of_simulations": 20,
        "opening_hour": 8,
        "closing_hour": 22,
        "daily_customers": 3000,
        "max_number_of_servers": 10,
        "min_service_time": 1,
        "avg_service_time": 2,
        "max_service_time": 8,
        "SLA": 0.9,
        "critical_avg_wait": 7,
        "hour_weights": [0.35, 0.50, 0.75, 0.95, 1.05, 1.10, 1.00, 0.95, 1.10, 1.35, 1.65, 1.45, 1.00, 0.55]}
      return demo_config
    if choice == "2":
      input_from_console()
      return None
    print("Please enter 1 or 2")

#retail_templates = {
      #"Weekday": [0.35, 0.50, 0.75, 0.95, 1.05, 1.10, 1.00, 0.95, 1.10, 1.35, 1.65, 1.45, 1.00, 0.55],
      #"Friday": [0.40, 0.55, 0.80, 1.00, 1.10, 1.15, 1.05, 1.00, 1.25, 1.60, 2.05, 1.80, 1.20, 0.65],
      #"Saturday": [0.55, 0.80, 1.05, 1.30, 1.45, 1.50, 1.40, 1.35, 1.45, 1.55, 1.60, 1.45, 1.05, 0.65]}

retail_templates = {
  "Weekday": [0.08, 0.05, 0.04, 0.04, 0.06, 0.10, 0.18, 0.32, 0.55, 0.78, 0.95, 1.08, 1.15, 1.10, 1.00, 0.96, 1.08, 1.30, 1.55, 1.45, 1.20, 0.88, 0.50, 0.22],
  "Friday": [0.08, 0.05, 0.04, 0.04, 0.06, 0.10, 0.18, 0.34, 0.58, 0.82, 1.00, 1.12, 1.18, 1.12, 1.05, 1.08, 1.28, 1.58, 1.92, 1.85, 1.55, 1.10, 0.62, 0.28],
  "Saturday": [0.10, 0.07, 0.05, 0.05, 0.06, 0.08, 0.12, 0.18, 0.30, 0.55, 0.88, 1.18, 1.38, 1.48, 1.52, 1.50, 1.42, 1.36, 1.40, 1.46, 1.34, 1.00, 0.62, 0.30],
  "Sunday": [0.09, 0.06, 0.05, 0.05, 0.05, 0.06, 0.08, 0.10, 0.16, 0.28, 0.52, 0.85, 1.10, 1.24, 1.30, 1.28, 1.18, 1.05, 0.96, 0.88, 0.72, 0.48, 0.26, 0.14]
}

def get_int(prompt, min_value=None, max_value=None):
  while True:
    try:
      value = int(input(prompt))
      if min_value is not None and value < min_value:
        print(f"Value must be >= {int(min_value)}")
        continue
      if max_value is not None and value > max_value:
        print(f"Value must be <= {int(max_value)}")
        continue
      return value
    except ValueError:
      print("Please enter a valid integer")

def get_float(prompt, min_value=None, max_value=None):
  while True:
    try:
      value = float(input(prompt))
      if min_value is not None and value < min_value:
        print(f"Value must be >= {int(min_value)}")
        continue
      if max_value is not None and value > max_value:
        print(f"Value must be <= {int(max_value)}")
        continue
      return value
    except ValueError:
      print("Please enter a valid number")

def input_day():
  while True:
    print("Available day profiles:", ", ".join(day_profiles))
    day = input("Choose a day: ")
    if day not in day_profiles:
      print("Choose a day from the list")
    else:
      return day

def input_service_time():
  min_service_time = get_float("Enter minimal possible service time in minutes: ", 0)
  while True:
    avg_service_time = get_float("Enter average service time in minutes: ", min_service_time)
    if avg_service_time == min_service_time:
      print("Average service time must be greater than minimal service time")
    else:
      break
  while True:
    max_service_time = get_float("Enter maximal realistic service time in minutes: ", avg_service_time)
    if max_service_time == avg_service_time:
      print("Maximum service time must be greater than average service time")
    else:
      break
  return min_service_time, avg_service_time, max_service_time

def get_operating_hours():
  if config["opening_hour"] < config["closing_hour"]:
    operating_hours = list(range(config["opening_hour"], config["closing_hour"]))
  elif config["opening_hour"] == config["closing_hour"]:
    operating_hours = list(range(24))
  else:
    operating_hours = list(range(config["opening_hour"], 24)) + list(range(0, config["closing_hour"]))
  return operating_hours

def input_hour_weights():
  operating_hours = get_operating_hours()
  print("Choose traffic profile input method:")
  print("1 - Retail template")
  print("2 - Flat profile")
  print("3 - Manual input")
  choice = input("Enter 1, 2 or 3: ").strip()
  if choice == "1":
    hour_weights = [retail_templates[config["day"]][h] for h in operating_hours]
    print("Using retail template")
  elif choice == "2":
    hour_weights = [1.0]*len(operating_hours)
    print("Using flat profile")
  elif choice == "3":
    hour_weights = []
    print("Enter relative traffic weights for each hour")
    print("1.0 = normal hour, >1.0 = busier, <1.0 = quieter")
    print("Weights will be normalized automatically")
    for hour in operating_hours:
      while True:
        try:
          value = float(input(f"{hour:02d}:00–{hour+1:02d}:00: "))
          if value < 0:
            print("Weight must be >=0")
            continue
          hour_weights.append(value)
          break
        except ValueError:
          print("Please enter a valid number (1.0 = normal hour, >1.0 = busier, <1.0 = quieter)")
    print("Using manual input")
  else:
    print("Invalid choice -> Using default template")

  print("\nTraffic profile preview:")
  for hour, hour_weight in zip(operating_hours, hour_weights):
    next_hour = (hour + 1) % 24
    bar = "██" * max(0, int(hour_weight*5))
    print(f"{hour:02d}:00–{next_hour:02d}:00  {hour_weight:.2f}  {bar}")
  return hour_weights

def input_from_console():
  config["day"] = input_day()
  config["number_of_simulations"] = get_int("Enter number of simulations for analysis: ", 1, None)

  print("Enter operating hours of the day from (integer from 0 to 23)")
  print("Hint: for 24/7 operations enter the same value for opening and closing hour")
  config["opening_hour"] = get_int("Enter opening hour: ", 0, 23)
  config["closing_hour"] = get_int("Enter closing hour: ", 0, 23)
  config["max_number_of_servers"] = get_int("Enter maximum number of servers avaliable: ", 1, None)
  config["min_service_time"], config["avg_service_time"], config["max_service_time"] = input_service_time()

  config["daily_customers"]= get_int("Enter average number of customers expected throughout the day: ", 1, None)
  config["critical_avg_wait"] = get_int("Enter critical average waiting time in queue for customers in minutes: ", 1, None)
  config["SLA"] = get_float("Enter service level target in % (e.g. 90 for 90%): ", 0, 100)/100
  config["hour_weights"] = input_hour_weights()

def count_lambda_per_hour():
  lambda_per_hour = []
  for hour_weight in config["hour_weights"]:
    lambda_per_hour.append(int(hour_weight/sum(config["hour_weights"])*config["daily_customers"]))
  return lambda_per_hour

def generate_servers(s):
  servers = []
  for i in range(s):
    servers.append(Server(i, 0, 0))
  return servers

def generate_clients_for_day():
  clients = []
  hour_start_time = 0
  next_client_id = 0
  config["lambda_per_hour"] = count_lambda_per_hour()
  clients_per_hour = [int(x) for x in np.random.poisson(config["lambda_per_hour"])]
  for hour in range(len(clients_per_hour)):
    arrival_times = []
    for i in range(clients_per_hour[hour]):
      arrival_times.append(hour_start_time + random.uniform(0,60))
    arrival_times.sort()
    for arrival_time in arrival_times:
      client = Client(next_client_id, arrival_time, None, None)
      clients.append(client)
      next_client_id += 1
    hour_start_time += 60
  return clients, clients_per_hour

def generate_service_time():
  min_t = config["min_service_time"]
  mean_t = config["avg_service_time"]
  max_t = config["max_service_time"]
  scale = mean_t - min_t
  while True:
    service_time = min_t + np.random.exponential(scale)
    if service_time <= max_t:
      return service_time

def check_free_servers(servers):
  for server in servers:
    if server.status == 0:
      return server
  return None

def find_next_free_server(servers):
  busy_servers = []
  for server in servers:
    if server.status == 1:
      busy_servers.append(server)
  if not busy_servers:
    return None, inf
  else:
    next_free_server = min(busy_servers, key=lambda x: x.time_to_free)
    return next_free_server, next_free_server.time_to_free

def check_next_event(next_arrival_time, next_free_server_time):
  if next_arrival_time < next_free_server_time:
    next_event = "arrival"
  elif next_arrival_time == next_free_server_time and next_arrival_time == inf:
    next_event = None
  else:
    next_event = "service_end"
  return next_event

def simulate_day (clients, number_of_servers):
  current_time = 0
  servers = generate_servers(number_of_servers)
  queue = deque([])
  next_arrival_id = 0
  next_arrival_time = clients[next_arrival_id].arrival_time
  while True:
    next_free_server, next_service_end_time = find_next_free_server(servers)
    next_event = check_next_event(next_arrival_time, next_service_end_time)
    if next_event == "arrival":
      current_time = next_arrival_time
      free_server = check_free_servers(servers)
      if free_server is not None:
        free_server.status = 1
        free_server.time_to_free = next_arrival_time + generate_service_time()
        clients[next_arrival_id].service_start_time = current_time
        clients[next_arrival_id].service_end_time = free_server.time_to_free
      else:
        queue.append(clients[next_arrival_id])
      next_arrival_id += 1
      if next_arrival_id == len(clients):
        next_arrival_time = inf
      else:
        next_arrival_time = clients[next_arrival_id].arrival_time
    elif next_event == "service_end":
      current_time = next_free_server.time_to_free
      if queue:
        queue[0].service_start_time = current_time
        queue[0].service_end_time = current_time + generate_service_time()
        next_free_server.status = 1
        next_free_server.time_to_free = queue[0].service_end_time
        queue.popleft()
      else:
        next_free_server.status = 0
        next_free_server.time_to_free = inf
    else:
      break
  return clients

def evaluate_day(clients, clients_per_hour):
  avg_wait_per_hour = []
  max_wait_per_hour = []
  avg_total_time_per_hour = []
  i = 0
  for number_of_clients_per_hour in clients_per_hour:
    avg_wait = 0
    max_wait = 0
    avg_total_time = 0
    if number_of_clients_per_hour == 0:
      avg_wait_per_hour.append(0)
      max_wait_per_hour.append(0)
      avg_total_time_per_hour.append(0)
    else:
      for client_id in range(number_of_clients_per_hour):
        avg_wait += clients[client_id+i].get_queue_time()
        max_wait = max(max_wait, clients[client_id+i].get_queue_time())
        avg_total_time += clients[client_id+i].get_total_time()
      avg_wait_per_hour.append(round((avg_wait/number_of_clients_per_hour), 2))
      max_wait_per_hour.append(round(max_wait,2))
      avg_total_time_per_hour.append(round((avg_total_time/number_of_clients_per_hour),2))
    i += number_of_clients_per_hour
  return avg_wait_per_hour, max_wait_per_hour, avg_total_time_per_hour

def multiple_simulations (number_of_simulations):
  operating_hours = get_operating_hours()
  avg_wait_3d_matrix = np.zeros((number_of_simulations, config["max_number_of_servers"], len(operating_hours)))
  for simulation in range(number_of_simulations):
    clients, clients_per_hour = generate_clients_for_day()
    for number_of_server in range(1, config["max_number_of_servers"]+1):
      for client in clients:
        client.service_start_time = None
        client.service_end_time = None
      clients = simulate_day(clients, number_of_server)
      avg_wait_per_hour, max_wait_per_hour, avg_total_time_per_hour = evaluate_day(clients, clients_per_hour)
      avg_wait_3d_matrix[simulation, number_of_server-1, :] = avg_wait_per_hour
  return avg_wait_3d_matrix

def create_critical_wait_matrix():
  operating_hours = get_operating_hours()
  servers = config["max_number_of_servers"]
  mu = 1/config["avg_service_time"]
  critical_wait_matrix = np.zeros((servers, len(operating_hours)))
  for s in range(1, servers+1):
    for h in range(len(operating_hours)):
      lambda_hour = config["lambda_per_hour"][h]
      rho = lambda_hour/(s*mu*60)
      critical_wait_matrix[s-1, h] = config["critical_avg_wait"]*(1+0.5*rho)
  return critical_wait_matrix

def optimal_number_of_servers(avg_wait_3d_matrix):
  critical_wait_matrix = create_critical_wait_matrix()
  sla_success_matrix = avg_wait_3d_matrix <= critical_wait_matrix
  sla_probability = np.mean(sla_success_matrix, axis=0)
  sla_ok = sla_probability >= config["SLA"]
  required_servers = np.where(np.any(sla_ok, axis=0), np.argmax(sla_ok, axis=0) + 1, -1)
  return required_servers, sla_probability

def Analytics(avg_wait_3d_matrix):
  operating_hours = get_operating_hours()
  average_w = np.mean(avg_wait_3d_matrix, axis=0)
  optimal_n, sla_probability = optimal_number_of_servers(avg_wait_3d_matrix)
  hours = [f"{h:02d}:00" for h in operating_hours]
  servers = [str(s) for s in range(1, config["max_number_of_servers"] + 1)]

  run_name = f"{config['day']}_{config['number_of_simulations']}_simulations"
  os.makedirs(run_name, exist_ok=True)

  print(optimal_n)
  print(average_w)
  print(np.char.add(np.round(sla_probability*100).astype(int).astype(str), "%"))

  with open(f"{run_name}/simulation_configuration.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["parameter", "value"])
    for key, value in config.items():
      if isinstance(value, list):
        value = ", ".join(map(str, value))
      writer.writerow([key, value])

  with open(f"{run_name}/avg_wait_matrix.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["servers/hours"] + hours)
    for i in range(average_w.shape[0]):
      writer.writerow([servers[i]] + list(np.round(average_w[i], 2)))

  with open(f"{run_name}/sla_probability_matrix.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["servers/hours"] + hours)
    for i in range(sla_probability.shape[0]):
      row = [f"{int(round(x * 100))}%" for x in sla_probability[i]]
      writer.writerow([servers[i]] + row)

  with open(f"{run_name}/required_servers_by_hour.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["hour", "required_servers"])
    for i in range(len(optimal_n)):
      value = f">{config['max_number_of_servers']}" if optimal_n[i] == -1 else int(optimal_n[i])
      writer.writerow([hours[i], value])

  plt.figure(figsize=(14, 6))
  vmin = 0
  vmax = config["critical_avg_wait"]*1.5
  levels = np.linspace(vmin, vmax, 100)
  norm = colors.BoundaryNorm(levels, ncolors=256)
  plt.imshow(average_w, aspect="auto", cmap="RdYlGn_r", norm = norm)
  for i in range(average_w.shape[0]):
    for j in range(average_w.shape[1]):
      plt.text(j, i, round(average_w[i, j], 2), ha="center", va="center", color="black", fontsize=8)

  plt.colorbar(label="Average wait time (minutes)")
  plt.xticks(range(len(hours)), hours, rotation=45)
  plt.yticks(range(len(servers)), servers)
  plt.xlabel("Hour")
  plt.ylabel("Number of servers")
  plt.title("Average Waiting Time Heatmap")
  plt.tight_layout()
  plt.savefig(f"{run_name}/avg_wait_heatmap.png", dpi=300)
  plt.close()

  plt.figure(figsize=(14, 6))
  levels = np.linspace(vmin, vmax, 100)
  norm = colors.BoundaryNorm(levels, ncolors=256)

  plt.imshow(sla_probability, aspect="auto", cmap="RdYlGn", vmin=0, vmax=1)
  for i in range(sla_probability.shape[0]):
    for j in range(sla_probability.shape[1]):
      plt.text(j, i, f"{round(sla_probability[i,j]*100, 2)}%", ha="center", va="center", color="black", fontsize=8)

  cbar = plt.colorbar()
  cbar.set_label("Probability of meeting SLA")
  cbar.ax.set_yticklabels(["0%","20%","40%","60%","80%","100%"])
  plt.xticks(range(len(hours)), hours, rotation=45)
  plt.yticks(range(len(servers)), servers)
  plt.xlabel("Hour")
  plt.ylabel("Number of servers")
  plt.title("SLA Probability Heatmap")
  plt.tight_layout()
  plt.savefig(f"{run_name}/sla_probability_heatmap.png", dpi=300)
  plt.close()

def main():
  global config
  config = {}
  demo = start_menu()
  if demo is not None:
    config = demo
  sim = multiple_simulations(config["number_of_simulations"])
  Analytics(sim)
main()

